added CRA tasks

diff --git a/.github/workflows/ibm-roks.yml b/.github/workflows/ibm-roks.yml
--- a/.github/workflows/ibm-roks.yml
+++ b/.github/workflows/ibm-roks.yml
@@ -34,7 +34,9 @@ env:
   DEPLOYMENT_NAME: trader
   CLUSTER_NAMESPACE: trader-gha-test
   EVIDENCE_DIR: evidence-repo
-  PORT: 5001
+  TOOLCHAIN_REGION: us-south   
+  TOOLCHAIN_ID: 286e3b40-5099-4d87-9f12-57d2e425c64b
+  REGION_ID: dal08  
 
 jobs:
   setup-build-publish-deploy:
@@ -135,19 +137,10 @@ jobs:
       run: echo $COMMITTED_AT
       env:
         COMMITTED_AT: ${{ steps.author-date.outputs.result }}
-
-    - name: Check docker
-      run: |
-        set -x
-        docker version
-        docker images
       
     - name: discovery
       continue-on-error: false    
       env:
-        TOOLCHAIN_REGION: us-south   
-        TOOLCHAIN_ID: 286e3b40-5099-4d87-9f12-57d2e425c64b
-        REGION_ID: dal08
         DIRECTORY_NAME: .
         PIPELINE_DEBUG: 1
         COMMITTED_AT: ${{ steps.author-date.outputs.result }}
@@ -159,8 +152,6 @@ jobs:
         OTC_BROKER_BASE_URL="https://otcbroker.devopsinsights.cloud.ibm.com"    
         
         REPO_DIR_PATH="$GITHUB_WORKSPACE"
-        ls -la
-        ls -la $REPO_DIR_PATH
         
         echo "Fetching users's token"
         ibmcloud config --check-version false
@@ -190,23 +181,6 @@ jobs:
           echo "Error IBM Code Risk Analyzer is not supported in ${REGION_ID}"
           exit 1
         fi
-          # create a dry-run k8s secret of type docker-registry to obtain 
-          # the pull secrets for the base image used in the dockerfile
-          # this is optional, but sometimes useful, for example when using
-          # UBI images from RedHat
-           
-         # if [ -f "/properties/build-baseimage-auth-user" ] \
-         #   && [ -f "/secrets/build-baseimage-auth-password" ] \
-         #   && [ -f "/properties/build-baseimage-auth-host" ]; then
-         #   echo "Adding pull secrets to access base image registry $(cat /properties/build-baseimage-auth-host)"
-         #   kubectl create secret --dry-run=client --output=json \
-         #     docker-registry registry-dockerconfig-secret \
-         #     --docker-username="$(cat /properties/build-baseimage-auth-user)" \
-         #     --docker-password="$(cat /secrets/build-baseimage-auth-password)" \
-         #     --docker-server="$(cat /properties/build-baseimage-auth-host)" \
-         #     --docker-email="$(cat /properties/build-baseimage-auth-email)" | \
-         #     jq -r '.data[".dockerconfigjson"]' | base64 -d > config.json
-         # fi
          
         echo "Repo URL: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
         echo "Branch: $GITHUB_REF"
@@ -222,9 +196,7 @@ jobs:
           -commitTimestamp "$COMMITTED_AT" \
           -toolchainid "${TOOLCHAIN_ID}"
 
- 
- 
- 
+  
   va-scan:
     name: Vulnarability advisor scan
     runs-on: ubuntu-latest
@@ -357,10 +329,363 @@ jobs:
     #    kubectl apply -f service.yaml
     #    kubectl get services -o wide
 
+
+  cra-vulnerability-scan:
+    name: cra-vulnerability-scan
+    runs-on: ubuntu-latest
+    needs: cra-discovery
+    container: icr.io/continuous-delivery/cra-vulnerability:release.1561
+    environment: production
+    outputs:
+      cra-vulnerability-scan-result: ${{ steps.remediation.outputs.cra-vulnerability-scan-result }}    
+    steps:
+    - name: Update git
+      run: |
+        set -x +e
+        uname -a
+        git --version
+        add-apt-repository ppa:git-core/ppa -y
+        apt-get update
+        apt-get install git -y
+        git --version
+        set -e
+        
+        
+    - name: Checkout
+      uses: actions/checkout@v2
+    
+    - name: Get timestamp
+      uses: actions/github-script@v3.1.0
+      id: author-date
+      with:
+        github-token: ${{secrets.GITHUB_TOKEN}}
+        script: |
+          const commit_details = await github.git.getCommit({owner: context.repo.owner, repo: context.repo.repo, commit_sha: context.sha});
+          return commit_details.data.author.date
+      
+    - name: Check timestamp
+      run: echo $COMMITTED_AT
+      env:
+        COMMITTED_AT: ${{ steps.author-date.outputs.result }}
+
+    
+    - name: remediation
+      id: remediation
+      continue-on-error: true
+      env:
+        DIRECTORY_NAME: .
+        PIPELINE_DEBUG: 1
+        COMMITTED_AT: ${{ steps.author-date.outputs.result }}
+        
+      run: |
+        set -x
+        API_ENDPOINT="https://cloud.ibm.com"
+        OTC_BROKER_BASE_URL="https://otcbroker.devopsinsights.cloud.ibm.com"    
+        
+        REPO_DIR_PATH="$GITHUB_WORKSPACE"
+        ls -la
+        ls -la $REPO_DIR_PATH
+        
+        echo "Fetching users's token"
+        ibmcloud config --check-version false
+        ibmcloud login -a $API_ENDPOINT -r $TOOLCHAIN_REGION --apikey $IBM_CLOUD_API_KEY
+        export IBM_CLOUD_BEARER=$(ibmcloud iam oauth-tokens --output JSON | jq -r '.iam_token' | awk '{ print $2 }')
+ 
+        echo "Fetching service urls for user's data"
+        HTTP_RESPONSE=$(curl --silent --write-out "HTTPSTATUS:%{http_code}" \
+            -X GET "${OTC_BROKER_BASE_URL}/globalauth/toolchainids/${TOOLCHAIN_ID}" \
+            --header "Authorization: Bearer ${IBM_CLOUD_BEARER}")
+        HTTP_STATUS=$(echo $HTTP_RESPONSE | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
+        if [ "$HTTP_STATUS" -eq 401 -o "$HTTP_STATUS" -eq 403 ]; then
+          echo ""
+          echo "Error authenticating user for toolchain_id: ${TOOLCHAIN_ID}"
+          echo "Please verify the Devops Insights card has been added to your toolchain and the api-key has access."
+          exit 1
+        fi
+        if [ "$HTTP_STATUS" -ne 200 ]; then
+          echo ""
+          echo "Error! Please try again."
+          exit 1
+        fi
+        HTTP_BODY=$(echo $HTTP_RESPONSE | sed -e 's/HTTPSTATUS\:.*//g')
+        gitsecureUrl=$(echo ${HTTP_BODY} | jq -r '.service_urls.gitsecure')
+        if [ -z "$gitsecureUrl" -o "$gitsecureUrl" = "null" ]; then
+          echo ""
+          echo "Error IBM Code Risk Analyzer is not supported in ${REGION_ID}"
+          exit 1
+        fi
+
+        vcuratorUrl=$(echo ${HTTP_BODY} | jq -r '.service_urls.vcurator')
+
+        if [ -z "$vcuratorUrl" -o "$vcuratorUrl" = "null" ]; then
+          echo "Error fetching the vcurator url."
+          exit 1
+        fi
+        
+        touch results-status.txt
+                    
+        /gitsecure/vulnerability-task \
+            -giturl "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" \
+            -gitbranch "$GITHUB_REF" \
+            -rigserviceapi "${gitsecureUrl}" \
+            -runid "$GITHUB_RUN_ID" \
+            -commitid "$GITHUB_SHA" \
+            -security_advisory_svc "${vcuratorUrl}" \
+            -results_status "./results-status.txt" \
+            -results_evidence "./gitsecure-vulnerability-results.json" \
+            -toolchainid "${TOOLCHAIN_ID}" \
+            -comment_md "./vulnerability-comment.md"        
+        
+        ls -la
+        RESULT=$(cat results-status.txt)
+        echo "RESULT=$RESULT"
+
+        cat gitsecure-vulnerability-results.json
+        cat vulnerability-comment.md
+        echo '::set-output name=cra-vulnerability-scan-result::$RESULT'
+        
+        if [ $RESULT != 'success' ]; then
+          echo "Scan failed."
+          exit 1
+        fi
+
+
+  cra-cis-check:
+    name: cra-cis-check
+    runs-on: ubuntu-latest
+    needs: cra-discovery
+    container: icr.io/continuous-delivery/cra-cis:release.1567
+    environment: production
+    outputs:
+      cra-cis-check-result: ${{ steps.cis.outputs.cra-cis-check-result }}    
+    steps:
+    - name: Update git
+      run: |
+        set -x +e
+        uname -a
+        git --version
+        add-apt-repository ppa:git-core/ppa -y
+        apt-get update
+        apt-get install git -y
+        git --version
+        set -e
+        
+        
+    - name: Checkout
+      uses: actions/checkout@v2
+
+    - name: cis
+      id: cis
+      continue-on-error: false
+      env:
+        DIRECTORY_NAME: .
+        PIPELINE_DEBUG: 1
+        
+      run: |
+        set -x
+        API_ENDPOINT="https://cloud.ibm.com"
+        OTC_BROKER_BASE_URL="https://otcbroker.devopsinsights.cloud.ibm.com"    
+        
+        REPO_DIR_PATH="$GITHUB_WORKSPACE"
+        
+        whoami
+        
+        echo "Home is $HOME"
+        
+        ls -la /github/home/        
+        
+        echo "Fetching users's token"
+        ibmcloud config --check-version false
+        
+        ls -la /github/home/
+        ls -la /github/home/.bluemix
+        
+        ibmcloud login -a $API_ENDPOINT -r $TOOLCHAIN_REGION --apikey $IBM_CLOUD_API_KEY
+        export IBM_CLOUD_BEARER=$(ibmcloud iam oauth-tokens --output JSON | jq -r '.iam_token' | awk '{ print $2 }')
+ 
+        echo "Fetching service urls for user's data"
+        HTTP_RESPONSE=$(curl --silent --write-out "HTTPSTATUS:%{http_code}" \
+            -X GET "${OTC_BROKER_BASE_URL}/globalauth/toolchainids/${TOOLCHAIN_ID}" \
+            --header "Authorization: Bearer ${IBM_CLOUD_BEARER}")
+        HTTP_STATUS=$(echo $HTTP_RESPONSE | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
+        if [ "$HTTP_STATUS" -eq 401 -o "$HTTP_STATUS" -eq 403 ]; then
+          echo ""
+          echo "Error authenticating user for toolchain_id: ${TOOLCHAIN_ID}"
+          echo "Please verify the Devops Insights card has been added to your toolchain and the api-key has access."
+          exit 1
+        fi
+        if [ "$HTTP_STATUS" -ne 200 ]; then
+          echo ""
+          echo "Error! Please try again."
+          exit 1
+        fi
+        HTTP_BODY=$(echo $HTTP_RESPONSE | sed -e 's/HTTPSTATUS\:.*//g')
+        gitsecureUrl=$(echo ${HTTP_BODY} | jq -r '.service_urls.gitsecure')
+        if [ -z "$gitsecureUrl" -o "$gitsecureUrl" = "null" ]; then
+          echo ""
+          echo "Error IBM Code Risk Analyzer is not supported in ${REGION_ID}"
+          exit 1
+        fi
+
+        
+        touch results-status.txt
+        
+        /usr/local/bin/deploy-analytic \
+          -giturl "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" \
+          -gitbranch "$GITHUB_REF" \
+          -repodir $REPO_DIR_PATH \
+          -apiservice "${gitsecureUrl}" \
+          -runid "$GITHUB_RUN_ID" \
+          -commitid "$GITHUB_SHA" \
+          -results_status "./results-status.txt" \
+          -results_evidence "./gitsecure-cis-results.json" \
+          -toolchainid "${TOOLCHAIN_ID}" \
+          -comment_md "./gitsecure-cis-comment.md"
+    
+        
+        ls -la
+        RESULT=$(cat results-status.txt)
+        echo "RESULT=$RESULT"
+
+        cat gitsecure-cis-results.json
+        cat gitsecure-cis-comment.md
+        echo '::set-output name=cra-cis-check-result::$RESULT'
+        
+        if [ $RESULT != 'success' ]; then
+          echo "Scan failed."
+          exit 1
+        fi
+
+  cra-bom:
+    name: cra-bom
+    runs-on: ubuntu-latest
+    needs: cra-discovery
+    container: icr.io/continuous-delivery/cra-bom:release.1497
+    environment: production
+    outputs:
+      cra-bom-result: ${{ steps.bom.outputs.cra-bom-result }}    
+    steps:
+    - name: Update git
+      run: |
+        set -x +e
+        uname -a
+        git --version
+        add-apt-repository ppa:git-core/ppa -y
+        apt-get update
+        apt-get install git -y
+        git --version
+        set -e
+        
+    - name: bom
+      id: bom
+      continue-on-error: false
+      env:
+        TOKEN: ${{ secrets.GITHUB_TOKEN }}    
+        PR_NUMBER: ${{ github.event.number }}
+        BASE_SHA:  ${{ github.event.pull_request.base.sha }}
+        TARGET_BRANCH: $GITHUB_BASE_REF       
+        DIRECTORY_NAME: .
+        PIPELINE_DEBUG: 1
+        
+      run: |
+        set -x +e
+        API_ENDPOINT="https://cloud.ibm.com"
+        OTC_BROKER_BASE_URL="https://otcbroker.devopsinsights.cloud.ibm.com"    
+        
+        REPO_DIR_PATH="$GITHUB_WORKSPACE"
+        
+        whoami
+        
+        CURRENT_USER=$(whoami)
+        
+        echo "Home is $HOME"
+        
+        ls -la /github/home/
+        
+        sudo mkdir /github/home/.bluemix
+        sudo chown -R $CURRENT_USER:$CURRENT_USER /github/home/.bluemix
+        
+        echo "Fetching users's token"
+        #commented out due to permision error - Configuration error: mkdir /github/home/.bluemix: permission denied
+        ibmcloud config --check-version false
+        ibmcloud login -a $API_ENDPOINT -r $TOOLCHAIN_REGION --apikey $IBM_CLOUD_API_KEY
+        export IBM_CLOUD_BEARER=$(ibmcloud iam oauth-tokens --output JSON | jq -r '.iam_token' | awk '{ print $2 }')
+ 
+        echo "Fetching service urls for user's data"
+        HTTP_RESPONSE=$(curl --silent --write-out "HTTPSTATUS:%{http_code}" \
+            -X GET "${OTC_BROKER_BASE_URL}/globalauth/toolchainids/${TOOLCHAIN_ID}" \
+            --header "Authorization: Bearer ${IBM_CLOUD_BEARER}")
+        HTTP_STATUS=$(echo $HTTP_RESPONSE | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
+        if [ "$HTTP_STATUS" -eq 401 -o "$HTTP_STATUS" -eq 403 ]; then
+          echo ""
+          echo "Error authenticating user for toolchain_id: ${TOOLCHAIN_ID}"
+          echo "Please verify the Devops Insights card has been added to your toolchain and the api-key has access."
+          exit 1
+        fi
+        if [ "$HTTP_STATUS" -ne 200 ]; then
+          echo ""
+          echo "Error! Please try again."
+          exit 1
+        fi
+        HTTP_BODY=$(echo $HTTP_RESPONSE | sed -e 's/HTTPSTATUS\:.*//g')
+        gitsecureUrl=$(echo ${HTTP_BODY} | jq -r '.service_urls.gitsecure')
+        if [ -z "$gitsecureUrl" -o "$gitsecureUrl" = "null" ]; then
+          echo ""
+          echo "Error IBM Code Risk Analyzer is not supported in ${REGION_ID}"
+          exit 1
+        fi
+
+        uiUrl=$(echo ${HTTP_BODY} | jq -r '.service_urls.controlcenter')
+        if [ -z "$uiUrl" -o "$uiUrl" = "null" ]; then
+          echo "Error fetching the ui url."
+          exit 1
+        fi
+        
+        echo "Current dir: $(pwd)"
+        echo "changing permissions for $(pwd)"
+        
+        sudo chown -R $CURRENT_USER:$CURRENT_USER $(pwd)
+
+        touch results-status.txt
+        
+        echo "BASE_SHA $BASE_SHA"
+        echo "TARGET_BRANCH $TARGET_BRANCH"
+        echo "GITHUB_BASE_REF $GITHUB_BASE_REF"
+        echo "GITHUB_HEAD_REF $GITHUB_HEAD_REF"
+        echo "GITHUB_REF $GITHUB_REF"
+
+        /gitsecure/bom-task \
+          -giturl "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" \
+          -gitbranch "$GITHUB_REF" \
+          -rigserviceapi ${gitsecureUrl} \
+          -ui_url ${uiUrl} \
+          -pr "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/pull/$PR_NUMBER" \
+          -runid "$GITHUB_RUN_ID" \
+          -commitid "$GITHUB_SHA" \
+          -target_commitid "$BASE_SHA" \
+          -target_branch "$GITHUB_BASE_REF" \
+          -results_status "./results-status.txt" \
+          -results_evidence "./gitsecure-bom-results.json" \
+          -toolchainid "${TOOLCHAIN_ID}" \
+          -comment_md "./gitsecure-bom-comment.md"
+
+        ls -la
+        RESULT=$(cat results-status.txt)
+        echo "RESULT=$RESULT"
+
+        cat gitsecure-bom-results.json
+        cat gitsecure-bom-comment.md
+        echo '::set-output name=cra-bom-result::$RESULT'
+        
+        if [ $RESULT != 'success' ]; then
+          echo "Scan failed."
+          exit 1
+        fi
+        
   publish-evidence:
     name: Publish evidence to evidence repo
     runs-on: ubuntu-latest
-    needs: [setup-build-publish-deploy, va-scan]
+    needs: [setup-build-publish-deploy, va-scan, cra-vulnerability-scan, cra-cis-check, cra-bom]
     steps:
     # Checkout repo   
     - name: Checkout
@@ -404,6 +729,10 @@ jobs:
         
         echo "$( jq '(.evidences[] | select(.evidence_type_id == "com.ibm.unit_tests") | .result) |= "${{needs.setup-build-publish-deploy.outputs.unit-test-result}}"' $EVIDENCE_DIR/raw/cd/$NEW_UUID2/summary.json )" > $EVIDENCE_DIR/raw/cd/$NEW_UUID2/summary.json
         echo "$( jq '(.evidences[] | select(.evidence_type_id == "com.ibm.cloud.image_vulnerability_scan") | .result) |= "${{needs.va-scan.outputs.va-scan-status}}"' $EVIDENCE_DIR/raw/cd/$NEW_UUID2/summary.json )" > $EVIDENCE_DIR/raw/cd/$NEW_UUID2/summary.json
+        
+        echo "$( jq '(.evidences[] | select(.evidence_type_id == "com.ibm.code_vulnerability_scan") | .result) |= "${{needs.cra-vulnerability-scan.outputs.cra-vulnerability-scan-result}}"' $EVIDENCE_DIR/raw/cd/$NEW_UUID2/summary.json )" > $EVIDENCE_DIR/raw/cd/$NEW_UUID2/summary.json
+        echo "$( jq '(.evidences[] | select(.evidence_type_id == "com.ibm.code_cis_check") | .result) |= "${{needs.cra-cis-check.outputs.cra-cis-check-result}}"' $EVIDENCE_DIR/raw/cd/$NEW_UUID2/summary.json )" > $EVIDENCE_DIR/raw/cd/$NEW_UUID2/summary.json
+        echo "$( jq '(.evidences[] | select(.evidence_type_id == "com.ibm.code_bom_check") | .result) |= "${{needs.cra-bom.outputs.cra-bom-result}}"' $EVIDENCE_DIR/raw/cd/$NEW_UUID2/summary.json )" > $EVIDENCE_DIR/raw/cd/$NEW_UUID2/summary.json
     
     - name: Commit report
       env:
