discovery2

diff --git a/.github/workflows/ibm-roks.yml b/.github/workflows/ibm-roks.yml
--- a/.github/workflows/ibm-roks.yml
+++ b/.github/workflows/ibm-roks.yml
@@ -106,9 +106,8 @@ jobs:
       uses: actions/checkout@v2
       
     - name: discovery
-      continue-on-error: true    
+      continue-on-error: false    
       env:
-        API_KEY: ${{secrets.API_KEY}}
         TOOLCHAIN_REGION: us-south   
         TOOLCHAIN_ID: 286e3b40-5099-4d87-9f12-57d2e425c64b
         REGION_ID: dal08
@@ -116,17 +115,76 @@ jobs:
         PIPELINE_DEBUG: 1
         
       run: |
-        set -x +e
+        set -x
         pwd
         API_ENDPOINT="https://cloud.ibm.com"
-        OTC_BROKER_BASE_URL="https://otcbroker.devopsinsights.cloud.ibm.com"       
+        OTC_BROKER_BASE_URL="https://otcbroker.devopsinsights.cloud.ibm.com"    
+        
+        REPO_DIR_PATH="$GITHUB_WORKSPACE"
+        ls -la $REPO_DIR_PATH
         
         echo "Fetching users's token"
         ibmcloud config --check-version false
-        ibmcloud login -a $API_ENDPOINT -r $TOOLCHAIN_REGION --apikey $API_KEY
+        ibmcloud login -a $API_ENDPOINT -r $TOOLCHAIN_REGION --apikey $IBM_CLOUD_API_KEY
         export IBM_CLOUD_BEARER=$(ibmcloud iam oauth-tokens --output JSON | jq -r '.iam_token' | awk '{ print $2 }')
  
-  
+        echo "Fetching service urls for user's data"
+        HTTP_RESPONSE=$(curl --silent --write-out "HTTPSTATUS:%{http_code}" \
+            -X GET "${OTC_BROKER_BASE_URL}/globalauth/toolchainids/${TOOLCHAIN_ID}" \
+            --header "Authorization: Bearer ${IBM_CLOUD_BEARER}")
+        HTTP_STATUS=$(echo $HTTP_RESPONSE | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
+        if [ "$HTTP_STATUS" -eq 401 -o "$HTTP_STATUS" -eq 403 ]; then
+          echo ""
+          echo "Error authenticating user for toolchain_id: ${TOOLCHAIN_ID}"
+          echo "Please verify the Devops Insights card has been added to your toolchain and the api-key has access."
+          exit 1
+        fi
+        if [ "$HTTP_STATUS" -ne 200 ]; then
+          echo ""
+          echo "Error! Please try again."
+          exit 1
+        fi
+        HTTP_BODY=$(echo $HTTP_RESPONSE | sed -e 's/HTTPSTATUS\:.*//g')
+        gitsecureUrl=$(echo ${HTTP_BODY} | jq -r '.service_urls.gitsecure')
+        if [ -z "$gitsecureUrl" -o "$gitsecureUrl" = "null" ]; then
+          echo ""
+          echo "Error IBM Code Risk Analyzer is not supported in ${REGION_ID}"
+          exit 1
+        fi
+          # create a dry-run k8s secret of type docker-registry to obtain 
+          # the pull secrets for the base image used in the dockerfile
+          # this is optional, but sometimes useful, for example when using
+          # UBI images from RedHat
+           
+         # if [ -f "/properties/build-baseimage-auth-user" ] \
+         #   && [ -f "/secrets/build-baseimage-auth-password" ] \
+         #   && [ -f "/properties/build-baseimage-auth-host" ]; then
+         #   echo "Adding pull secrets to access base image registry $(cat /properties/build-baseimage-auth-host)"
+         #   kubectl create secret --dry-run=client --output=json \
+         #     docker-registry registry-dockerconfig-secret \
+         #     --docker-username="$(cat /properties/build-baseimage-auth-user)" \
+         #     --docker-password="$(cat /secrets/build-baseimage-auth-password)" \
+         #     --docker-server="$(cat /properties/build-baseimage-auth-host)" \
+         #     --docker-email="$(cat /properties/build-baseimage-auth-email)" | \
+         #     jq -r '.data[".dockerconfigjson"]' | base64 -d > config.json
+         # fi
+         
+        echo "Repo URL: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
+        echo "Branch: $GITHUB_REF"
+        echo "Commit id: $GITHUB_SHA"
+        
+         
+        /usr/local/bin/discovery \
+          -giturl "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" \
+          -gitbranch "$GITHUB_REF" \
+          -repodir $REPO_DIR_PATH  \
+          -rigapi "${gitsecureUrl}" \
+          -commitid "$GITHUB_SHA" \
+          -toolchainid "${TOOLCHAIN_ID}"
+
+ 
+ 
+ 
   va-scan:
     name: Vulnarability advisor scan
     runs-on: ubuntu-latest
