added remediation

diff --git a/.github/workflows/pr-workflow.yml b/.github/workflows/pr-workflow.yml
--- a/.github/workflows/pr-workflow.yml
+++ b/.github/workflows/pr-workflow.yml
@@ -74,7 +74,6 @@ jobs:
       
     - name: discovery
       continue-on-error: false
-      if: "false"
       env:
         TOOLCHAIN_REGION: us-south   
         TOOLCHAIN_ID: 286e3b40-5099-4d87-9f12-57d2e425c64b
@@ -121,23 +120,6 @@ jobs:
           echo "Error IBM Code Risk Analyzer is not supported in ${REGION_ID}"
           exit 1
         fi
-          # create a dry-run k8s secret of type docker-registry to obtain 
-          # the pull secrets for the base image used in the dockerfile
-          # this is optional, but sometimes useful, for example when using
-          # UBI images from RedHat
-           
-         # if [ -f "/properties/build-baseimage-auth-user" ] \
-         #   && [ -f "/secrets/build-baseimage-auth-password" ] \
-         #   && [ -f "/properties/build-baseimage-auth-host" ]; then
-         #   echo "Adding pull secrets to access base image registry $(cat /properties/build-baseimage-auth-host)"
-         #   kubectl create secret --dry-run=client --output=json \
-         #     docker-registry registry-dockerconfig-secret \
-         #     --docker-username="$(cat /properties/build-baseimage-auth-user)" \
-         #     --docker-password="$(cat /secrets/build-baseimage-auth-password)" \
-         #     --docker-server="$(cat /properties/build-baseimage-auth-host)" \
-         #     --docker-email="$(cat /properties/build-baseimage-auth-email)" | \
-         #     jq -r '.data[".dockerconfigjson"]' | base64 -d > config.json
-         # fi
          
         echo "Repo URL: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
         echo "Branch: $GITHUB_REF"
@@ -153,74 +135,117 @@ jobs:
           -commitTimestamp "$COMMITTED_AT" \
           -toolchainid "${TOOLCHAIN_ID}"
 
-  cra-vulnerability-scan-status-pending:
-    name: cra-vulnerability-scan-status-pending
-    needs: cra-discovery
+   
+  cra-vulnerability-scan:
+    name: cra-vulnerability-scan
     runs-on: ubuntu-latest
+    needs: cra-discovery
+    container: icr.io/continuous-delivery/cra-discovery:release.1571
     environment: production
+    outputs:
+      cra-vulnerability-scan-result: ${{ steps.remediation.outputs.cra-vulnerability-scan-result }}    
     steps:
-    - name: Checkout
-      uses: actions/checkout@v2  
-      
-    - name: Set up Python 3.x
-      uses: actions/setup-python@v2
-      
-    - name: Display the path
-      env:
-        TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      
+    - name: Update git
       run: |
-        import json
-        import os
-        import sys
-        import urllib.request
-        import urllib.parse
+        set -x +e
+        uname -a
+        git --version
+        add-apt-repository ppa:git-core/ppa -y
+        apt-get update
+        apt-get install git -y
+        git --version
+        set -e
         
-        state = "pending"
-        print(os.environ['GITHUB_SHA'])
-        revision = os.environ['GITHUB_SHA']
-        description = "PR Pipeline Status"
-        context = "cra-vulnerability-scan"
         
-        # compute the target url of this pipeline run
-        target_url = "https://github.com/gasgithub/trader/actions"
-        
-        # Create the request object according to the Git Flavor API
-        api_prefix=""
-        status_url = ("https://api.github.com" + api_prefix + "/repos/" + os.environ['GITHUB_REPOSITORY'] + "/statuses/" + revision)        
-        
-        print("status url: " + status_url)
-        
-        data = {
-          "state": state,
-          "target_url": target_url,
-          "description": description,
-          "context": context
-        }   
-        print("token: " + os.environ['TOKEN'])
-        req = urllib.request.Request(
-          status_url,
-          data=json.dumps(data).encode('utf8'),
-          headers={
-            "content-type": "application/json",
-            "Authorization": "Bearer " + os.environ['TOKEN']
-          },
-          method="POST"
-        )
-        req.add_header("User-Agent", "GH actions PR workflow")
- 
-        with urllib.request.urlopen(req) as resp:
-          if not str(resp.status).startswith("2"):
-            print("Error: %d" % (resp.status))
-            print(resp.read())
-            sys.exit(1)
-          else:
-            print(" commit status '" + state + "' has been set on " + os.environ['GITHUB_REPOSITORY'] + "#" + revision)
-            print("Status: %d" % (resp.status))
-            print(resp.read())
-            sys.exit(0)
+    - name: Checkout
+      uses: actions/checkout@v2
+    
+    - name: Get timestamp
+      uses: actions/github-script@v3.1.0
+      id: author-date
+      with:
+        github-token: ${{secrets.GITHUB_TOKEN}}
+        script: |
+          const commit_details = await github.git.getCommit({owner: context.repo.owner, repo: context.repo.repo, commit_sha: context.sha});
+          return commit_details.data.author.date
+      
+    - name: Check timestamp
+      run: echo $COMMITTED_AT
+      env:
+        COMMITTED_AT: ${{ steps.author-date.outputs.result }}
 
-      shell: python      
+    
+    - name: remediation
+      id: remediation
+      continue-on-error: false
+      env:
+        TOOLCHAIN_REGION: us-south   
+        TOOLCHAIN_ID: 286e3b40-5099-4d87-9f12-57d2e425c64b
+        REGION_ID: dal08
+        DIRECTORY_NAME: .
+        PIPELINE_DEBUG: 1
+        COMMITTED_AT: ${{ steps.author-date.outputs.result }}
+        
+      run: |
+        set -x
+
+        API_ENDPOINT="https://cloud.ibm.com"
+        OTC_BROKER_BASE_URL="https://otcbroker.devopsinsights.cloud.ibm.com"    
+        
+        REPO_DIR_PATH="$GITHUB_WORKSPACE"
+        ls -la
+        ls -la $REPO_DIR_PATH
+        
+        echo "Fetching users's token"
+        ibmcloud config --check-version false
+        ibmcloud login -a $API_ENDPOINT -r $TOOLCHAIN_REGION --apikey $IBM_CLOUD_API_KEY
+        export IBM_CLOUD_BEARER=$(ibmcloud iam oauth-tokens --output JSON | jq -r '.iam_token' | awk '{ print $2 }')
  
- 
- 
+        echo "Fetching service urls for user's data"
+        HTTP_RESPONSE=$(curl --silent --write-out "HTTPSTATUS:%{http_code}" \
+            -X GET "${OTC_BROKER_BASE_URL}/globalauth/toolchainids/${TOOLCHAIN_ID}" \
+            --header "Authorization: Bearer ${IBM_CLOUD_BEARER}")
+        HTTP_STATUS=$(echo $HTTP_RESPONSE | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
+        if [ "$HTTP_STATUS" -eq 401 -o "$HTTP_STATUS" -eq 403 ]; then
+          echo ""
+          echo "Error authenticating user for toolchain_id: ${TOOLCHAIN_ID}"
+          echo "Please verify the Devops Insights card has been added to your toolchain and the api-key has access."
+          exit 1
+        fi
+        if [ "$HTTP_STATUS" -ne 200 ]; then
+          echo ""
+          echo "Error! Please try again."
+          exit 1
+        fi
+        HTTP_BODY=$(echo $HTTP_RESPONSE | sed -e 's/HTTPSTATUS\:.*//g')
+        gitsecureUrl=$(echo ${HTTP_BODY} | jq -r '.service_urls.gitsecure')
+        if [ -z "$gitsecureUrl" -o "$gitsecureUrl" = "null" ]; then
+          echo ""
+          echo "Error IBM Code Risk Analyzer is not supported in ${REGION_ID}"
+          exit 1
+        fi
+
+        vcuratorUrl=$(echo ${HTTP_BODY} | jq -r '.service_urls.vcurator')
+
+        if [ -z "$vcuratorUrl" -o "$vcuratorUrl" = "null" ]; then
+          echo "Error fetching the vcurator url."
+          exit 1
+        fi
+        
+        RESULT_STATUS=""
+        
+        /gitsecure/vulnerability-task \
+            -giturl "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" \
+            -gitbranch "$GITHUB_REF" \
+            -rigserviceapi "${gitsecureUrl}" \
+            -runid "$GITHUB_RUN_ID" \
+            -commitid "$GITHUB_SHA" \
+            -comment_md "./comment_md.json" \
+            -security_advisory_svc "${vcuratorUrl}" \
+            -results_status "$(RESULT_STATUS)" \
+            -results_evidence "./gitsecure-vulnerability-results.json" \
+            -toolchainid "${TOOLCHAIN_ID}" \
+            -comment_md "./vulnerability-comment.md"        
+        
+        echo "RESULT_STATUS: $RESULT_STATUS"
+        echo '::set-output name=cra-vulnerability-scan-result::$RESULT_STATUS'        
