add comment

diff --git a/.github/workflows/pr-workflow.yml b/.github/workflows/pr-workflow.yml
--- a/.github/workflows/pr-workflow.yml
+++ b/.github/workflows/pr-workflow.yml
@@ -177,7 +177,7 @@ jobs:
     
     - name: remediation
       id: remediation
-      continue-on-error: false
+      continue-on-error: true
       env:
         TOOLCHAIN_REGION: us-south   
         TOOLCHAIN_ID: 286e3b40-5099-4d87-9f12-57d2e425c64b
@@ -233,9 +233,7 @@ jobs:
         fi
         
         touch results-status.txt
-        
-        ls -la
-                
+                    
         /gitsecure/vulnerability-task \
             -giturl "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" \
             -gitbranch "$GITHUB_REF" \
@@ -249,7 +247,54 @@ jobs:
             -comment_md "./vulnerability-comment.md"        
         
         ls -la
-        cat results-status.txt
+        RESULT=$(cat results-status.txt)
+        echo "RESULT=$RESULT"
+
         cat gitsecure-vulnerability-results.json
         cat vulnerability-comment.md
-        echo '::set-output name=cra-vulnerability-scan-result::success'
+        echo '::set-output name=cra-vulnerability-scan-result::$RESULT'
+        
+        if [ $RESULT != 'success' ]; then
+          echo "Scan failed."
+          exit 1
+        fi
+
+    - name: Upload results
+      uses: actions/upload-artifact@v2
+      with:
+        name: comment_md
+        path: vulnerability-comment.md
+        
+  cra-vulnerability-scan-comment:
+    name: cra-vulnerability-scan-comment
+    runs-on: ubuntu-latest
+    needs: cra-vulnerability-scan
+    container: icr.io/continuous-delivery/cra-comm-editor:release.1519
+    environment: production
+    steps:
+    - name: Download results
+      uses: actions/download-artifact@v2
+      with:
+        name: comment_md
+        
+    - name: Add comment
+      env:
+        TOKEN: ${{ secrets.GITHUB_TOKEN }}    
+        PR_NUMBER: ${{ github.event.number }}
+        
+      run: |
+        set -x +e
+        COMMENT_FP=$(cat vulnerability-comment.md)
+        
+        /usr/local/bin/comm-editor \
+            -repo-url "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" \
+            -pr-url "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/pull/$PR_NUMBER" \
+            -token "$TOKEN" \
+            -comment-fp "$COMMENT_FP" \
+            -project-id "" \
+            -scm-type "github"
+        COMM_RESULT=$?
+        if [ "$COMM_RESULT" != "0" ]; then
+            echo "Error posting comment to pull request"
+            exit 1
+        fi
